### ISSUE TITLE
Does Beefy work on Ubuntu?

### ISSUE THREAD

**Issue by painkkiller** [chrisdickinson/beefy#110]
I used beefy on Windows 10 and everything was OK. Then I switched on to Ubuntu (so may be problem is not related to beefy, but to my knowledge of Ubuntu) and found that beefy not working on my project.
I have node.js v4.2.6
 What I did:
1. Installed beefy via npm globally.
2. cd to root of my project folder where file app.js is located
3. Run command: 
`beefy app.js --live`
It gives error /usr/bin/env: ‘node’: No such file or directory . But it worked in Windows!
I tried different paths `beefy /home/user/Desktop/project/app.js --live` but anyway I am getting this error. Thanks in advance.

**Comment by painkkiller** [comment]
Sorry after several minutes solved this issue with:
`sudo ln -s /usr/bin/nodejs /usr/bin/node`

and got another when running beefy:

`/usr/local/lib/node_modules/beefy/bin/beefy:13
    throw err
    ^

Error: Could not find a suitable bundler!
    at onglobals (/usr/local/lib/node_modules/beefy/lib/setup-bundlers.js:50:18)
    at /usr/local/lib/node_modules/beefy/node_modules/find-global-packages/index.js:40:25
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
`
But browserify is installed globally and I bundle files via terminal command
