### ISSUE TITLE
Beefy does not find bundlers when there's an alternate npm global install path

### ISSUE THREAD

**Issue by Sequoia** [chrisdickinson/beefy#70]
I install global packages in `~/npm/`.  `npm` exists in `/usr/bin`.  Beefy seems to rely on the location of `npm` when looking for bundlers rather than calling `which` on the actual executable (e.g. `watchify`).
- [installing global packages w/o root](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md)
- [npm prefix](https://docs.npmjs.com/misc/config#prefix)

When I add `console.log(dir[i])` in the for loop in `setup-bundlers.onglobals` I see that it's not looking in my `~/npm/` directory for browserify/watchify:

```
➜  beefy  cat ~/.npmrc 
prefix = /home/diamonds/npm
➜  beefy  which browserify
/home/diamonds/npm/bin/browserify
➜  beefy  which watchify 
/home/diamonds/npm/bin/watchify
➜  beefy  which npm
/usr/bin/npm
➜  beefy  cd -
~/treackpadello
➜  treackpadello git:(master) ✗ beefy         
>> entering setup-bundlers.onglobals
>> starting loop over dirs...
/usr/share/node-gyp
/usr/share/npm

/home/diamonds/npm/lib/node_modules/beefy/bin/beefy:13
    throw err;
          ^
Error: Could not find a suitable bundler!
    at onglobals (/home/diamonds/npm/lib/node_modules/beefy/lib/setup-bundlers.js:53:18)
    at /home/diamonds/npm/lib/node_modules/beefy/node_modules/find-global-packages/index.js:40:25
    at Object.cb [as oncomplete] (fs.js:168:19)
```

**Comment by wachunga** [comment]
This is also affecting me, apparently.

**Comment by hansent** [comment]
I trued sym-linking my brew npm into /usr/bin... that didn't help.  however `npm install -g browserify` did the trick

**Comment by rathorer** [comment]
had same problem, npm install -g browserify worked for me too

**Comment by mattdesl** [comment]
Also seeing this issue. I have `npm config prefix` set to a different path and `npm install -g` doesn't seem to solve this. 

For the record, Beefy might be able to utilize this:
https://www.npmjs.com/package/resolve-npm-which

**Comment by mark-hahn** [comment]
With this command
```
nohup beefy src/main.coffee 1340 --cwd www --live \
            -- -o bundle.js -t coffeeify > run.log 2>&1 &
```
I am seeing

```
Cannot find module '/home/mark/Dropbox/apps/tv/browserify' from '/home/mark/Dropbox/apps/tv'
```
even though browserify is global and the command `browserify` works from the command line.  I'll try making it local instead.

**Comment by mark-hahn** [comment]
I can't get beefy to find browserify no matter what I can think of to try.  Can someone show me a setup that works? 

- browserify project folder (local or global?)
- beefy project folder (local or global?)
- beefy startup (command line or node module?)
- entry file

**Comment by mattdesl** [comment]
If you can't get it to work @mark-hahn you may have better luck with one of these tools:

https://github.com/mattdesl/budo
https://github.com/maxogden/wzrd

**Comment by mark-hahn** [comment]
Thanks.   It's nice to know about these three options.

I got beefy to work by moving both beefy and browserify to local node_modules and removing the global installs.  I also switched to just running a node file in my root directory with the beefy server code.

**Comment by ajuc** [comment]
I had same problem, solved it by adding --browserify $(which browserify) to the beefy start script in package.json of my project.

**Comment by rocLv** [comment]
@ajuc This works for me.
