### ISSUE TITLE
Beefy is broken?

### ISSUE THREAD

**Issue by dcosson** [chrisdickinson/beefy#99]
I get the following error when running beefy in the simplest possible form, I'm on OSX El Capitan and Node 4.2.1.

```
beefy (v2.1.5) is listening on http://127.0.0.1:9966
200    7ms       530B  / (generated)
buffer.js:229
    buf.copy(buffer, pos);
        ^

TypeError: buf.copy is not a function
    at Function.Buffer.concat (buffer.js:229:9)
    at Stream.end (C:\Users\Tomasz\AppData\Roaming\npm\node_modules\beefy\lib\accumulate-error.js:25:26)
    at _end (C:\Users\Tomasz\AppData\Roaming\npm\node_modules\beefy\node_modules\through\index.js:61:9)
    at Stream.stream.end (C:\Users\Tomasz\AppData\Roaming\npm\node_modules\beefy\node_modules\through\index.js:70:5)
    at Stream.onend (stream.js:59:10)
    at emitNone (events.js:72:20)
    at Stream.emit (events.js:166:7)
    at drain (C:\Users\Tomasz\AppData\Roaming\npm\node_modules\beefy\node_modules\through\index.js:33:23)
    at Stream.stream.queue.stream.push (C:\Users\Tomasz\AppData\Roaming\npm\node_modules\beefy\node_modules\through\index.js:41:5)
    at Stream.end (C:\Users\Tomasz\AppData\Roaming\npm\node_modules\beefy\node_modules\through\index.js:17:35)
npm ERR! Test failed.  See above for more details.
```

The command I'm running is
```
beefy app/entry.js 
```

Then when I request `http://localhost:9966/bundle.js` beefy crashes with the buf error above.

It's certainly possible I'm hitting some weird edge case, but it really seems like beefy is just broken on the most common development environments for at least versions of node released in the past ~3 months. Seems like a pretty big issue...

**Comment by contra** [comment]
Also getting this on 5.2.0

**Comment by mattstyles** [comment]
Which browserify transforms are you using?

I got this with babelify but when I dropped it (just to glslify) it works fine, node 5.2.0.

Although live reload is behind but thats a separate issue.

**Comment by dfcreative** [comment]
After updating from 0.10 to 5.3.0 also started having this issue.

**Comment by shoshanaly** [comment]
I go this same error, and changing my dependencies from browserify 13 to 12 fixed it.
